spring:
  application:
    name: news
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudSimple?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cloudsimple.news.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
server:
  port: 8085
